var Articles =
[
	{
		title:"Data<morphose>",
		descHtml:"\<b\>blabla\</b\>",
		year: "2015",
		month: "OCT",
		themes: "éléctronique, imprimante 3d",
		imgUrl:"images/portfolio/pngs/apidotart2.png",
		tags:["electronique", "imprimante 3d"],
		contentHtml: "C'est à l'occasion du <a target='_blank' href='http://www.apidotart.com'>Hackaton Api Dot Art</a> au GoogleArtInstitute de Paris que j'ai pu m'amuser à la réalisation technique d'une procédure qui imprime en 3D une forme unique représentant les méta données d'une oeuvre d'art.\<br/\>\<br/\>  Projet en collaboration avec <br/><small><b>Barthelemy de Mazenod</b> | <b>Bastien Bouvier</b> | <b>Gaëtan Guironnet</b> |  <b>Hugo Villain</b> | <b>Miyö Van Stenis</b>  | <b>Raphaëlle Estorc</b> | <b>Tristram Gräbener</b> | <b>Valérie Marsaudon</b></small>\<br/\>\<br/\> Le code est disponible sur \<a target='_blank' href='http://github.com/tfrere/RobotRepo/tree/master/handOnLeap'\>Github\</a\> sous licence MIT.",
	},
	{
		title:"Interface homme machine",
		descHtml: "\<b\>blabla2\</b\>\<b\>blabla2\</b\>",
		year: "2015",
		month: "AOU",
		themes: "éléctronique, arduino, leap motion",
		imgUrl:"images/portfolio/pngs/bras.png",
		tags:["electronique", "arduino", "leap motion"],
		contentHtml: "Petit week-end de prototypage d'une main robot.<br/> Le but était d'avoir un robot reproduisant en direct le mouvement de la main du 'pilote'.<br/><br/> <b>Techniquement</b> le prototype est controllé par un arduino qui reçoit les informations d'un leap motion.\<br/\>\<br/\>\<img src='images/portfolio/bras.gif'/>\<br/\>\<br/\> \<br/\>  Projet en collaboration avec <br/><small><b>Anthony Lacroix</b> | <b>Thibaud Mertz</b></b></small>\<br/\>\<br/\>Le code est disponible sur \<a target='_blank' href='http://github.com/tfrere/RobotRepo/tree/master/dotart'\>Github\</a\> sous licence MIT.",
	},
	// {
	// 	title:"Design survival guide",
	// 	descHtml:"\<b\>blabla\</b\>",
	// 	year: "2014",
	// 	month: "NOV",
	// 	themes: "pédagogie, web, intégration",
	// 	imgUrl:"images/portfolio/pngs/apidotart2.png",
	// 	tags:["pédagogie", "web", "intégration"],
	// 	contentHtml: "Réalisation collaborative d'un survival guide pour des équipes de hackaton sans designer. C'est un condensé en une page, de toutes les ressources requises pour la création d'une identité graphique. \<br/\>\<br/\>\<a target='_blank' href='images/portfolio/design_survival_guide.pdf'\> Le pdf \</a\>",
	// },
	// {
	// 	title:"Pixel art",
	// 	descHtml:"\<b\>blabla\</b\>",
	// 	year: "2014",
	// 	month: "Fév",
	// 	themes: "programmation, illustration",
	// 	tags:["pixel art", "programmation", "illustration"],
	// 	contentHtml: "Réalisation d'une suite de textures au format xpixmap et png dans le cadre du développement d'un jeu en raycaster à 42.\<br/\>\<br/\> \<img src='images/portfolio/pngs/texture.png'\>",
	// },
	{
		title:"Recherches logo",
		descHtml: "\<b\>blabla2\</b\>\<b\>blabla2\</b\>",
		year: "2013",
		month: "MAI",
		themes: "logo, restaurant, végérarien",
		tags:["logo", "restaurant", "végétarien"],
		contentHtml: "Essais de logo pour un réstaurant végétarien fictif.\<br/\>\<br/\> \<img src='images/portfolio/jpgs/meethappy.jpg'\>",
	},
	{
		title:"Cartes de visites",
		descHtml:"\<b\>blabla\</b\>",
		year: "2012",
		month: "AOU",
		themes: "identité visuelle, imprimé",
		imgUrl:"images/portfolio/jpgs/carte2.jpg",
		tags:["carte de visite", "identité visuelle", "imprimé"],
		contentHtml: "Travail d'identité visuelle vintage sur carte de visite. Impression avec letterpressing chez <a target='_blank' href='http://www.elegantepress.com/'>ElegantPress</a>. \<br/\> <small>500 gsm radiant white letterPressing recto / verso. Bichromie</small> \<br/\>\<br/\> \<img src='images/portfolio/jpgs/carte2.jpg'\>",
	},
	{
		title:"Pochette d'album",
		descHtml:"\<b\>blabla\</b\>",
		year: "2012",
		month: "JUI",
		themes: "album, musique",
		imgUrl:"images/portfolio/jpgs/aos_final.jpg",
		tags:["album", "musique"],
		contentHtml: "Définition d'une identité visuelle et cover d'album pour le groupe Strasbourgeois Ash of Sound. <br/><br/> \<img src='images/portfolio/jpgs/aos_final.jpg'\> <a target='_blank' href='http://www.deezer.com/artist/341769'> Ecouter l'album</a><br/><br/>",
	},
	{
		title:"Modélisation",
		descHtml: "\<b\>blabla2\</b\>\<b\>blabla2\</b\>",
		year: "2011",
		month: "OCT",
		themes: "3D, Maya",
		imgUrl:"images/portfolio/jpgs/loco.jpg",
		tags:["3D", "Maya"],
		contentHtml: "Rush de 6h. Modélisation complexe sous maya. D'après photos. \<br/\>\<br/\>\<img src='images/portfolio/jpgs/loco.jpg'\>",
	}
];


export default Articles;